name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull gcampecino/squire-test:latest
    - name: Delete Old docker container
      run: sudo docker rm -f squire-test-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name squire-test-container --env-file .env gcampecino/squire-test
