name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t squire-test:latest .

    - name: Push Docker image to Docker Hub
      run: docker push squire-test:latest

    - name: Deploy to ec2 squire test server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker stop $(docker ps -a -q) || true 
          docker pull gcampecino/squire-test:latest
          docker run -d -p 80:80 gcampecino/squire-test:latest
        EOF

    
